package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/rafischer1/gmri_capstone_go_be/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Datum)
// DB Table: Plural (data)
// Resource: Plural (Data)
// Path: Plural (/data)
// View Template Folder: Plural (/templates/data/)

// DataResource is the resource for the Datum model
type DataResource struct {
	buffalo.Resource
}

// List gets all Data. This function is mapped to the path
// GET /data
func (v DataResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	data := &models.Data{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Data from the DB
	if err := q.All(data); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, data))
}

// Show gets the data for one Datum. This function is mapped to
// the path GET /data/{datum_id}
func (v DataResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Datum
	datum := &models.Datum{}

	// To find the Datum the parameter datum_id is used.
	if err := tx.Find(datum, c.Param("datum_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, datum))
}

// New renders the form for creating a new Datum.
// This function is mapped to the path GET /data/new
func (v DataResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Datum{}))
}

// Create adds a Datum to the DB. This function is mapped to the
// path POST /data
func (v DataResource) Create(c buffalo.Context) error {
	// Allocate an empty Datum
	datum := &models.Datum{}

	// Bind datum to the html form elements
	if err := c.Bind(datum); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(datum)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, datum))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Datum was created successfully")

	// and redirect to the data index page
	return c.Render(201, r.Auto(c, datum))
}

// Edit renders a edit form for a Datum. This function is
// mapped to the path GET /data/{datum_id}/edit
func (v DataResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Datum
	datum := &models.Datum{}

	if err := tx.Find(datum, c.Param("datum_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, datum))
}

// Update changes a Datum in the DB. This function is mapped to
// the path PUT /data/{datum_id}
func (v DataResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Datum
	datum := &models.Datum{}

	if err := tx.Find(datum, c.Param("datum_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Datum to the html form elements
	if err := c.Bind(datum); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(datum)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, datum))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Datum was updated successfully")

	// and redirect to the data index page
	return c.Render(200, r.Auto(c, datum))
}

// Destroy deletes a Datum from the DB. This function is mapped
// to the path DELETE /data/{datum_id}
func (v DataResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Datum
	datum := &models.Datum{}

	// To find the Datum the parameter datum_id is used.
	if err := tx.Find(datum, c.Param("datum_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(datum); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Datum was destroyed successfully")

	// Redirect to the data index page
	return c.Render(200, r.Auto(c, datum))
}
